### ISSUE TITLE
Possibilità di pioggia

### ISSUE THREAD

**Issue by cagnulein** [eutampieri/pymeteoam#2]
Hai trovato il modo di intercettare la probabilità di pioggia in percentuale senza fare un parsing della pagina html?
Grazie
Ciao

**Comment by eutampieri** [comment]
In realtà è uno scraping piuttosto facile, posso implementarlo se vuoi

**Comment by cagnulein** [comment]
mi faresti un piacere, si grazie. ho visto che usi pagine php che però non comprendono quel dato. o mi sono perso qualcosa?

**Comment by eutampieri** [comment]
No, le pagine PHP sono quelle dei grafici, e infatti li non c’è la probabilità

**Comment by cagnulein** [comment]
hah perchè io ho usato la funzione forecast_24h, tu invece parlavi della daily

**Comment by cagnulein** [comment]
la funzione daily mi da errore sia con py2 che py3, mi sa che hanno cambiato qualcosa sul sito. tu lo usi ancora?

**Comment by cagnulein** [comment]
```
  File "maranello.py", line 5, in <module>
    print(maranello.forecast_daily())
  File "/root/git-projects/pymeteoam/meteoam.py", line 85, in forecast_daily
    "place": soup.find("h3").find("a").text.capitalize(), "forecast": [(lambda x: {"day_of_week": dow[x[0].text], "extreme_weather": x[1].find("img")["alt"] if x[1].find("img") is not None else None, "weather": x[2].find("img")["alt"], "min_t": float(x[3].text.encode("utf-8").replace("°",'')), "max_t": float(x[4].text.encode("utf-8").replace("°",'')), "wind": x[5].find(attrs={"class":"badge"})["title"]})(r.find_all("td")) for r in soup.find_all("tr")[1:]]}
  File "/root/git-projects/pymeteoam/meteoam.py", line 85, in <listcomp>
    "place": soup.find("h3").find("a").text.capitalize(), "forecast": [(lambda x: {"day_of_week": dow[x[0].text], "extreme_weather": x[1].find("img")["alt"] if x[1].find("img") is not None else None, "weather": x[2].find("img")["alt"], "min_t": float(x[3].text.encode("utf-8").replace("°",'')), "max_t": float(x[4].text.encode("utf-8").replace("°",'')), "wind": x[5].find(attrs={"class":"badge"})["title"]})(r.find_all("td")) for r in soup.find_all("tr")[1:]]}
  File "/root/git-projects/pymeteoam/meteoam.py", line 85, in <lambda>
    "place": soup.find("h3").find("a").text.capitalize(), "forecast": [(lambda x: {"day_of_week": dow[x[0].text], "extreme_weather": x[1].find("img")["alt"] if x[1].find("img") is not None else None, "weather": x[2].find("img")["alt"], "min_t": float(x[3].text.encode("utf-8").replace("°",'')), "max_t": float(x[4].text.encode("utf-8").replace("°",'')), "wind": x[5].find(attrs={"class":"badge"})["title"]})(r.find_all("td")) for r in soup.find_all("tr")[1:]]}
TypeError: 'NoneType' object is not subscriptable
```

**Comment by eutampieri** [comment]
Potrebbe essere che non funzioni per l'issue #3 , prova a inizializzare con l'ID del paese, il numero che nell'URL delle previsioni è subito prima del nome della località

**Comment by cagnulein** [comment]
> Potrebbe essere che non funzioni per l'issue #3 , prova a inizializzare con l'ID del paese, il numero che nell'URL delle previsioni è subito prima del nome della località

sisi gia' sto facendo cosi.
comunque per il rain me lo sto implementando io, poi magari ti faccio una pull request specifica

**Comment by eutampieri** [comment]
Cioè la possibilità di pioggia?

> Il giorno 18 set 2019, alle ore 16:06, cagnulein <notifications@github.com> ha scritto:
> 
> comunque per il rain me lo sto implementando io, poi magari ti faccio una pull request specifica
> 
>

**Comment by cagnulein** [comment]
si esatto, finito. il codice e' un po' sporco ma funziona

**Comment by eutampieri** [comment]
Adesso sarebbe comodo aggiungere la percentuale di pioggia al risultato di `forecast_24h`

**Comment by eutampieri** [comment]
La massima giornaliera è disponibile, con la PR #4

**Comment by cagnulein** [comment]
> Adesso sarebbe comodo aggiungere la percentuale di pioggia al risultato di `forecast_24h`

quello se vuoi lo puoi fare tu :)

**Comment by cagnulein** [comment]
in sostanza quello che serviva a me era che alexa mi dicesse se oggi potevo andare in bici o meno :)

**Comment by eutampieri** [comment]
Ahah ok

**Comment by cagnulein** [comment]
@eutampieri mi spieghi come sei riuscito ad ottenere la url http://www.meteoam.it/sites/all/modules/custom/tempo_in_atto/highcharts/dati_temperature.php ?

Non riesco a capire come tu l'abbia trovato :O

**Comment by eutampieri** [comment]
Con i dev tool di qualche browser e guardando le richieste mentre aprivo i grafici
